insert into storage.buckets (id, name, public)
values ('listing-videos', 'listing-videos', true)
on conflict (id) do update
set public = excluded.public;

create table if not exists public.tiktok_connections (
  id uuid primary key default gen_random_uuid(),
  user_id text not null default 'admin',
  platform_account_label text,
  open_id text not null unique,
  display_name text,
  avatar_url text,
  access_token_encrypted text not null,
  refresh_token_encrypted text not null,
  scope text not null,
  access_token_expires_at timestamptz not null,
  refresh_token_expires_at timestamptz not null,
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now())
);

create table if not exists public.listing_videos (
  id uuid primary key default gen_random_uuid(),
  listing_id uuid not null references public.listings(id) on delete cascade,
  file_name text not null,
  video_url text not null,
  storage_path text not null unique,
  mime_type text not null,
  size_bytes bigint not null,
  duration_seconds integer,
  status text not null default 'ready',
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now())
);

create index if not exists listing_videos_listing_id_idx
  on public.listing_videos (listing_id, created_at desc);

create table if not exists public.tiktok_upload_jobs (
  id uuid primary key default gen_random_uuid(),
  listing_video_id uuid not null references public.listing_videos(id) on delete cascade,
  tiktok_connection_id uuid references public.tiktok_connections(id) on delete set null,
  publish_id text not null unique,
  mode text not null default 'draft_upload',
  status text not null default 'created',
  last_error text,
  requested_by_user_id text default 'admin',
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now())
);

create index if not exists tiktok_upload_jobs_listing_video_idx
  on public.tiktok_upload_jobs (listing_video_id, created_at desc);

create table if not exists public.audit_log (
  id bigint generated by default as identity primary key,
  actor text not null default 'admin',
  action text not null,
  entity_type text,
  entity_id text,
  details jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default timezone('utc', now())
);

create index if not exists audit_log_created_at_idx
  on public.audit_log (created_at desc);

drop trigger if exists tiktok_connections_set_updated_at on public.tiktok_connections;
create trigger tiktok_connections_set_updated_at
before update on public.tiktok_connections
for each row
execute function public.set_updated_at();

drop trigger if exists listing_videos_set_updated_at on public.listing_videos;
create trigger listing_videos_set_updated_at
before update on public.listing_videos
for each row
execute function public.set_updated_at();

drop trigger if exists tiktok_upload_jobs_set_updated_at on public.tiktok_upload_jobs;
create trigger tiktok_upload_jobs_set_updated_at
before update on public.tiktok_upload_jobs
for each row
execute function public.set_updated_at();

alter table public.tiktok_connections enable row level security;
alter table public.listing_videos enable row level security;
alter table public.tiktok_upload_jobs enable row level security;
alter table public.audit_log enable row level security;
